DROP TABLE IF EXISTS `payment`;

CREATE TABLE `payment` (
    ID VARCHAR(256) NOT NULL,
    ORDER_ID VARCHAR(256),
    TOTAL INT,
    USERNAME VARCHAR(256),
    STATUS VARCHAR(48),
    PRIMARY KEY (ID)
);
