DROP TABLE IF EXISTS `invoice`;

CREATE TABLE `INVOICE` (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ORDER_ID VARCHAR(256),
    PRODUCT VARCHAR(256),
    AMOUNT INTEGER,
    PRICE INT,
    TOTAL INT,
    USERNAME VARCHAR(256),
    ADDRESS VARCHAR(256),
    STATUS VARCHAR(48),
    PRIMARY KEY (ID)
);

CREATE TABLE ORDER_MESSAGE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ORDER_ID VARCHAR(256),
    PRODUCT VARCHAR(256),
    AMOUNT INTEGER,
    PRICE INTEGER,
    TOTAL INTEGER,
    USERNAME VARCHAR(256),
    ADDRESS VARCHAR(256),
    PRIMARY KEY (ID)
)